### PR TITLE
Fix locale

### PR DESCRIPTION
**Pull request by toanalien**
Error message:
```bash
$ locale
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
...
```

### CODE REVIEW

**Comment by daohoangson** [comment]
What is your use case for `locale`?

**Comment by toanalien** [comment]
> What is your use case for `locale`?

Error when I use `iconv` lib.

**Comment by daohoangson** [comment]
> Error when I use `iconv` lib.

Oh, can you share a reproducible piece of code? I noticed you made the change for apache variant. Not sure whether it's needed on the fpm variant too?

**Comment by toanalien** [comment]
```bash
$ php -r "setlocale(LC_CTYPE, 'en_US.UTF8'); echo iconv('utf-8', 'us-ascii//TRANSLIT', 'địch');"
```
expect output `dich` but in fact `??ch`

**Comment by daohoangson** [comment]
I have built `xfrocks/xenforo:php-apache-7.2.13d` with `locales-all` as suggested. Couldn't include locale for the fpm image though (I have noted about that in the README).

Please try the latest apache image and see whether it works for you and close this PR if possible. 

Thank you.

**Pull request closed without merging**
